; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	D:\Adam\Documents\libkoliba\fixslut.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	__real@0000000000000000
PUBLIC	__real@3df0000000000000
PUBLIC	_KOLIBA_FixSlut
EXTRN	__fltused:DWORD
;	COMDAT __real@0000000000000000
; File d:\adam\documents\libkoliba\fixslut.c
CONST	SEGMENT
__real@0000000000000000 DQ 00000000000000000r	; 0
CONST	ENDS
;	COMDAT __real@3df0000000000000
CONST	SEGMENT
__real@3df0000000000000 DQ 03df0000000000000r	; 2.32831e-010
; Function compile flags: /Ogtpy
CONST	ENDS
_TEXT	SEGMENT
_sLut$ = 8						; size = 4
_KOLIBA_FixSlut PROC
; Line 56
	push	esi
; Line 60
	mov	esi, DWORD PTR _sLut$[esp]
	test	esi, esi
	jne	SHORT $LN5@KOLIBA_Fix
	xor	eax, eax
	pop	esi
; Line 65
	ret	0
$LN5@KOLIBA_Fix:
; Line 62
	fld	QWORD PTR __real@3df0000000000000
	mov	ecx, 24					; 00000018H
	fldz
	mov	edx, esi
$LN4@KOLIBA_Fix:
; Line 63
	fld	QWORD PTR [edx]
	fabs
	fcomp	ST(2)
	fnstsw	ax
	test	ah, 65					; 00000041H
	jp	SHORT $LN3@KOLIBA_Fix
	fst	QWORD PTR [edx]
$LN3@KOLIBA_Fix:
; Line 62
	add	edx, 8
	dec	ecx
	jne	SHORT $LN4@KOLIBA_Fix
	fstp	ST(1)
; Line 64
	mov	eax, esi
	fstp	ST(0)
	pop	esi
; Line 65
	ret	0
_KOLIBA_FixSlut ENDP
_TEXT	ENDS
PUBLIC	_KOLIBA_FixFlut
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_fLut$ = 8						; size = 4
_KOLIBA_FixFlut PROC
; Line 70
	jmp	_KOLIBA_FixSlut
_KOLIBA_FixFlut ENDP
_TEXT	ENDS
END
