/*
	THIS IS STILL EXPERIMENTAL AND WILL BE COMPLETELY REDONE.
	SO PLEASE DO NOT USE IT IN ANY OFFICIAL WAY BECAUSE YOU
	WILL ONLY END UP FRUSTRATED.

	THE EVENTUAL MODULE WILL MOST LIKELY BE BASED ON C++ CLASSES
	RATHER THAN THE PLAIN C LIBRARY.
*/

#ifndef	KOLIBA_SWG
#define	KOLIBA_SWG

%module	koliba
%{
	#include "koliba.h"
%}

%include "koliba.h"

#endif
